
name: Claim

on:
  push:
    branches: ["main"]

jobs:
  build:
    env:
      PY_COLORS: "1"
    name: Install Dependencies
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        rangeIndex: ["2179 2184 1", "2179 2184 2", "2179 2184 3", "2179 2184 4", "2179 2184 5", "2179 2184 6", "2179 2184 7", "2184 2189 8", "2184 2189 9", "2184 2189 10", "2184 2189 11", "2184 2189 12", "2184 2189 13", "2184 2189 14", "2189 2194 15", "2189 2194 16", "2189 2194 17", "2189 2194 18", "2189 2194 19", "2189 2194 20", "2189 2194 21"]
    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      uses: actions/setup-node@v4
      with:
        node-version: 18
    - name: Setup Code
      run: |
        node index.js
        npm i
        node asis.js ${{secrets.WK_U}} ${{secrets.WK_I}} ${{secrets.WK_S}} ${{secrets.BK_U}}
        ls -la
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install
      run: |
        cd wkwk
        python -m pip install --upgrade pip wheel setuptools
        pip install -r requirements.txt
        sudo apt install -y ffmpeg
        sudo apt install -y google-chrome-stable
        seleniumbase install chromedriver
        sudo apt install -y xvfb
        export DISPLAY=:0
        /usr/bin/Xvfb :0 -screen 0 1024x768x24 &
        sleep 5
        xvfb-run python run.py ${{ matrix.rangeIndex }}
    - name: done
      run: exit
