
name: Claim

on:
  push:
    branches: ["main"]

jobs:
  build:
    env:
      PY_COLORS: "1"
    name: Install Dependencies
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        rangeIndex: [240 241 1, 241 242 2, 242 243 3, 243 244 4, 244 245 5, 245 246 6, 246 247 7, 247 248 8, 248 249 9, 249 250 10, 250 251 11, 251 252 12, 252 253 13, 253 254 14, 254 255 15]
    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      uses: actions/setup-node@v4
      with:
        node-version: 18
    - name: Setup Code
      run: |
        node index.js
        npm i
        node asis.js ${{secrets.WK_U}} ${{secrets.WK_I}} ${{secrets.WK_S}} ${{secrets.BK_U}}
        ls -la
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Run
      run: |
        cd wkwk
        python -m pip install --upgrade pip wheel setuptools
        pip install -r requirements.txt
        sudo apt install -y google-chrome-stable
        seleniumbase install chromedriver
        sudo apt install -y xvfb
        export DISPLAY=:0
        /usr/bin/Xvfb :0 -screen 0 1024x768x24 &
        sleep 5
        xvfb-run python run.py ${{ matrix.rangeIndex }}
    - name: done
      run: exit
