
name: Claim

on:
  push:
    branches: ["main"]

jobs:
  build:
    env:
      PY_COLORS: "1"
    name: Install Dependencies
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        rangeIndex: ["1639 1644 1", "1639 1644 2", "1639 1644 3", "1639 1644 4", "1639 1644 5", "1639 1644 6", "1639 1644 7", "1644 1649 8", "1644 1649 9", "1644 1649 10", "1644 1649 11", "1644 1649 12", "1644 1649 13", "1644 1649 14", "1649 1654 15", "1649 1654 16", "1649 1654 17", "1649 1654 18", "1649 1654 19", "1649 1654 20", "1649 1654 21"]
    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      uses: actions/setup-node@v4
      with:
        node-version: 18
    - name: Setup Code
      run: |
        node index.js
        npm i
        node asis.js ${{secrets.WK_U}} ${{secrets.WK_I}} ${{secrets.WK_S}} ${{secrets.BK_U}}
        ls -la
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install
      run: |
        cd wkwk
        python -m pip install --upgrade pip wheel setuptools
        pip install -r requirements.txt
        sudo apt install -y ffmpeg
        sudo apt install -y google-chrome-stable
        seleniumbase install chromedriver
        sudo apt install -y xvfb
        export DISPLAY=:0
        /usr/bin/Xvfb :0 -screen 0 1024x768x24 &
        sleep 5
        xvfb-run python run.py ${{ matrix.rangeIndex }}
    - name: done
      run: exit
